

top_tool_height: 100
left_tool_width: 150
view-size: 502
scene_geometry: [0, 0, 500, 500]


#----- ПАНЕЛИ ИНСТРУМЕНТОВ ------------

# панель инструментов горизонтальная

# расстояние от контейнера до краёв панели
h_tool_box_margin: [0, 0, 0, 0]

# расстояние между елементами внутри контейнера
h_tool_box_spacing: 0

h_top_buttons_size: 32

# панель инструментов вертикальная

# расстояние от контейнера до краёв панели
v_tool_box_margin: [0, 0, 0, 0]
# расстояние между елементами внутри контейнера
v_tool_box_spacing: 0

# кнопки панели


h_tool_box_Spacing: 0

# панель инструментов вертикальная

# расстояние от контейнера до краёв панели
v_tool_box_margin: [0, 0, 0, 0]
# расстояние между елементами внутри контейнера
v_tool_box_Spacing: 0

v_top_buttons_size: 30

# кнопки панели

top_buttons: ['Stretch', 'close_game']

